# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Haguichi
description: "Haguichi provides a graphical frontend for Hamachi on Linux"
author: "Stephen Brandt"
author_website: "https://stephenbrandt.com"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://haguichi.net" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
collections:
  donations:
    output: false
  downloads:
    output: false
  faqs:
    output: false
  post_tags:
    output: true
    permalink: /news/tag/:name/
  screenshots:
    output: false
  sections:
    output: false
statcounter:
  project: 5831480
  invisible: 1
  security: 67e436cf
  https: 1

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
